# This workflow is for execution purposes only
# The code below is not very useful for the challenge (trust me)

name: Challenge
run-name: Run ${{ inputs.uuid }}

on: 
  workflow_dispatch:
    inputs:
      uuid:
        description: 'Run UUID'     
        required: true
        type: string
      version:
        description: 'Package Version (x.y.z)'     
        required: true
        type: string
      logs_password:
        description: 'Logs Password'     
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Run challenge
        run: |
          export VERSION=$(jq -r '.inputs.version' $GITHUB_EVENT_PATH)
          echo "::add-mask::$VERSION"
          npm start > ./output.txt 2>&1

      - name: Encrypt logs
        if: always()
        run: |
          export LOGS_PASSWORD=$(jq -r '.inputs.logs_password' $GITHUB_EVENT_PATH)
          echo "::add-mask::$LOGS_PASSWORD"
          zip -P "$LOGS_PASSWORD" output.zip ./output.txt

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output
          path: output.zip
          retention-days: 1
