name: Test
run-name: Receiving Workflow [${{ inputs.uuid }}]

on: 
  workflow_dispatch:
    inputs:
      uuid:
        description: 'Run UUID'     
        required: true
        type: string
      typescript_version:
        description: 'Typescript version (x.y.z)'     
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run test
        run: |
          echo "::add-mask::COUCOUUU" 
          echo "::add-mask::${{ github.event.inputs.typescript_version }}" 
          echo "COUCOUUU toi"
          sed -r -i 's/5.7.2/${{ github.event.inputs.typescript_version }}/' package.json > ./output.txt 2>&1
          npm install > ./output.txt 2>&1
          npm test > ./output.txt 2>&1
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output
          path: output.txt
