name: Test

on: 
  workflow_dispatch:
    inputs:
      tabler_version:
        description: 'Typescript version (x.y.z)'     
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set Typescript version
        run: sed -r -i 's/__version__/${{ github.event.inputs.typescript_version }}/' package.json
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
