name: Test
run-name: Receiving Workflow [${{ inputs.uuid }}]

on: 
  workflow_dispatch:
    inputs:
      uuid:
        description: 'Run UUID'     
        required: true
        type: string
      version:
        description: 'Typescript version (x.y.z)'     
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run test
        run: |
          export VERSION=$(jq -r '.inputs.version' $GITHUB_EVENT_PATH)
          echo "::add-mask::$VERSION"
          ./test.sh > ./output.txt 2>&1
      - name: Passwd
        if: always()
        run: |
          zip -p "pass123" output-pass.zip ./output.txt
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output
          path: output.txt
          retention-days: 1
          compression-level: 9
